// <auto-generated />
using ILikeCardGames.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ILikeCardGames.Migrations
{
    [DbContext(typeof(ILikeCardGamesDbContext))]
    partial class ILikeCardGamesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ILikeCardGames.Models.Account.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.HasKey("AccountId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ILikeCardGames.Models.Account.AccountLoginInformation", b =>
                {
                    b.Property<int>("AccountLoginInformationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountLoginInformationId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("HashedAndSaltedPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountLoginInformationId");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountLoginInformations");
                });

            modelBuilder.Entity("ILikeCardGames.Models.Account.AccountLoginInformation", b =>
                {
                    b.HasOne("ILikeCardGames.Models.Account.Account", "Account")
                        .WithMany("AccountLoginInformations")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ILikeCardGames.Models.Account.Account", b =>
                {
                    b.Navigation("AccountLoginInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
